# Generated by Django 5.2 on 2025-05-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
